###
GET http://localhost:3003/api/blogs/


###
POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "FSO in a Closed World",
    "author": "Charles Babbage",
    "url": "https://www.wikipedia.org/",
    "likes": 5
}

###
GET http://localhost:3003/api/blogs/3
